# 006 - DML Commands (INSERT UPDATE DELETE)

In [1]:
import pandas as pd
import numpy as np

In [16]:
df_customer = pd.read_csv('data/customers.csv')

df_customer.head()

   id first_name  country  score
0   4     Martin  Germany    500
1   1      Maria  Germany    350
2   3      Georg       UK    750
3   2       John      USA    900
4   5      Peter      USA      0

```SQL
INSERT INTO customers (id, first_name, country, score)
VALUES
    (6,'Anna','USA',NULL),
    (7,'Sam',NULL,100)
```

In [17]:
nuevos_datos = pd.DataFrame([
    {"id": 6, "first_name": "Anna", 'country': "USA", 'score': None},
    {"id": 7, "first_name": "Sam", 'country': None, 'score': 100}
])

df_customer = pd.concat([df_customer, nuevos_datos], ignore_index=True)

In [19]:
df_customer

   id first_name  country  score
0   4     Martin  Germany  500.0
1   1      Maria  Germany  350.0
2   3      Georg       UK  750.0
3   2       John      USA  900.0
4   5      Peter      USA    0.0
5   6       Anna      USA    NaN
6   7        Sam     None  100.0

In [20]:
bad_data = pd.DataFrame([
    {'id':9,'first_name': 'USA', 'country':'Max','score':'200'}
])

df_customer = pd.concat([df_customer, bad_data], ignore_index=True)

In [22]:
df_customer = df_customer[df_customer['id'] != 9]

In [23]:
df_customer

   id first_name  country  score
0   4     Martin  Germany  500.0
1   1      Maria  Germany  350.0
2   3      Georg       UK  750.0
3   2       John      USA  900.0
4   5      Peter      USA    0.0
5   6       Anna      USA    NaN
6   7        Sam     None  100.0

# Copy data from 'customers' table into 'persons'

```SQL
INSERT INTO persons (id, person_name, birthday, phone)
SELECT
    id,
    first_name,
    NULL,
    'Unkown'
FROM customers
```

# Change the score of customer with ID 6 to 0

```SQL
UPDATE customers
SET score = 0
WHERE id BETWEEN 0 and 6;
```

In [24]:
df_customer.loc[df_customer['id'].between(0,6), 'score'] = 0

In [25]:
df_customer

   id first_name  country  score
0   4     Martin  Germany      0
1   1      Maria  Germany      0
2   3      Georg       UK      0
3   2       John      USA      0
4   5      Peter      USA      0
5   6       Anna      USA      0
6   7        Sam     None  100.0

```SQL
UPDATE customers
SET
    score = 0,
    country = 'UK'
WHERE id BETWEEN 0 and 6;
```

In [27]:
df_customer.loc[df_customer['id'].between(0,6), ['score','country']] = [10,'UK']

In [28]:
df_customer

   id first_name country  score
0   4     Martin      UK     10
1   1      Maria      UK     10
2   3      Georg      UK     10
3   2       John      UK     10
4   5      Peter      UK     10
5   6       Anna      UK     10
6   7        Sam    None  100.0