# 007 - Joins in SQL

In [2]:
import pandas as pd
import numpy as np

In [9]:
df_customers = pd.read_csv('data/customers.csv')
df_orders = pd.read_csv('data/orders.csv')

df_customers

   id first_name  country  score
0   4     Martin  Germany    500
1   1      Maria  Germany    350
2   3      Georg       UK    750
3   2       John      USA    900
4   5      Peter      USA      0

In [10]:
df_orders

   order_id  customer_id  order_date  sales
0      1001            1  2021-01-11     35
1      1002            2  2021-04-05     15
2      1003            3  2021-06-18     20
3      1004            6  2021-08-31     10

# INNER JOIN

### Only Matching Data

![Inner Join](Pictures/Inner_Join.png)

### SQL TASK 1
#### Get all customers along with their orders, but only for customers who have placed an order

```SQL
SELECT
    *
FROM customers c
INNER JOIN orders o ON c.id = o.customer_id;
```

In [12]:
df_result = pd.merge(
    df_customers,
    df_orders,
    left_on='id',
    right_on='customer_id',
    how='inner'
)

df_final = df_result[['id','first_name','order_id','sales']]

df_final

   id first_name  order_id  sales
0   1      Maria      1001     35
1   3      Georg      1003     20
2   2       John      1002     15

# LEFT JOIN

### Returns All rows from left and Only Matching From Right

![Left Join](Pictures/Left_Join.png)

### SQL TASK 2

#### Get all customers along with their orders, including those without orders

```SQL
SELECT
    c.id,
    c.first_name,
    o.order_id,
    o.sales
FROM customers c
LEFT JOIN orders o ON c.id = o.customer_id;
```

In [14]:
df_result_left = pd.merge(
    df_customers,
    df_orders,
    left_on = 'id',
    right_on = 'customer_id',
    how = 'left'
)

df_final_left = df_result_left[['id','first_name','order_id','sales']]

df_final_left

   id first_name  order_id  sales
0   4     Martin       NaN    NaN
1   1      Maria    1001.0   35.0
2   3      Georg    1003.0   20.0
3   2       John    1002.0   15.0
4   5      Peter       NaN    NaN

### INNER JOIN

### Returns All Rows from Right and Only Matching From Left

![right Join](Pictures/Right_Join.png)

### SQL TASK 3

#### Get all customers along with their orders, including orders without matching customers

```SQL
SELECT
    c.id,
    c.first_name,
    o.order_id,
    o.sales
FROM customers c
RIGHT JOIN orders o ON c.id = o.customer_id;
```

In [15]:
df_result_right = pd.merge(
    df_customers,
    df_orders,
    left_on = 'id',
    right_on = 'customer_id',
    how='right'
)

df_final_right = df_result_right[['id','first_name','order_id','sales']]

df_final_right

    id first_name  order_id  sales
0  1.0      Maria      1001     35
1  2.0       John      1002     15
2  3.0      Georg      1003     20
3  NaN        NaN      1004     10

### FULL JOIN

#### Returns All Rows from Both Tables

![Full Join](Pictures/Full_Join.png)

### SQL TASK 4

#### Get all customers and all orders, even if there's no match

```SQL
SELECT
    c.id,
    c.first_name,
    o.order_id,
    o.sales
FROM customers c
FULL JOIN orders o ON c.id = o.customer_id;
```

In [18]:
df_result_full = pd.merge(
    df_customers,
    df_orders,
    left_on = 'id',
    right_on = 'customer_id',
    how='outer'
)

df_final_full = df_result_full[['id','first_name','order_id','sales']]

df_final_full

    id first_name  order_id  sales
0  1.0      Maria    1001.0   35.0
1  2.0       John    1002.0   15.0
2  3.0      Georg    1003.0   20.0
3  4.0     Martin       NaN    NaN
4  5.0      Peter       NaN    NaN
5  NaN        NaN    1004.0   10.0