# Multi Join Table

In [1]:
import pandas as pd
import numpy as np

In [7]:
df_customers = pd.read_csv('data/sales_customers.csv')
df_employees = pd.read_csv('data/sales_employees.csv')
df_orders = pd.read_csv('data/sales_orders.csv')
df_orderarchive = pd.read_csv('data/sales_ordersarchive.csv')
df_products = pd.read_csv('data/sales_products.csv')

df_products

   productid product     category  price
0        101  Bottle  Accessories     10
1        102    Tire  Accessories     15
2        103   Socks     Clothing     20
3        104    Caps     Clothing     25
4        105  Gloves     Clothing     30

### SQL TASK

#### Using SalesDB, Retrieve a list of all orders, along with the related customer, product, and employee details

**For each order, desplay**
- Order Id
- Customer's name
- Product name
- Sales amount
- Product price
- Salesperson's name

```SQL
SELECT
    o.orderid,
    o.sales,
    c.firstname AS CustomerFirstName,
    c.lastname AS CustomerLastName,
    p.product As ProductName,
    p.price,
    e.firstname AS EmployeeFirstName,
    e.lastname AS EmployeeLastName
FROM sales.orders AS o
LEFT JOIN sales.customers AS c ON o.customerid = c.customerid
LEFT JOIN sales.products AS p On o.productid = p.productid
LEFT JOIN sales.employees AS e ON o.salespersonid = e.employeeid;
```

In [8]:
# 1. Unimos Orders con Customers
df_final = df_orders.merge(df_customers, left_on='customerid', right_on='customerid', how='left')

# 2. Unimos con Products
df_final = df_final.merge(df_products, left_on='productid', right_on='productid', how='left')

# 3. Unimos con Employees
df_final = df_final.merge(df_employees, left_on='salespersonid', right_on='employeeid', how='left')

# 4. Seleccionamos y renombramos las columnas (El SELECT AS de SQL)
df_final = df_final[[
    'orderid', 
    'sales', 
    'firstname_x', 'lastname_x',  # Nombres de clientes
    'product', 'price', 
    'firstname_y', 'lastname_y'   # Nombres de empleados
]].rename(columns={
    'firstname_x': 'CustomerFirstName',
    'lastname_x': 'CustomerLastName',
    'product': 'ProductName',
    'firstname_y': 'EmployeeFirstName',
    'lastname_y': 'EmployeeLastName'
})

df_final

,orderid,sales,CustomerFirstName,CustomerLastName,ProductName,price,EmployeeFirstName,EmployeeLastName
0,1,10,Kevin,Brown,Bottle,10,Mary,NaN
1,2,15,Mary,NaN,Tire,15,Mary,NaN
2,3,20,Jossef,Goldberg,Bottle,10,Carol,Baker
3,4,60,Jossef,Goldberg,Gloves,30,Mary,NaN
4,5,25,Kevin,Brown,Caps,25,Carol,Baker
5,6,50,Mary,NaN,Caps,25,Carol,Baker
6,7,30,Jossef,Goldberg,Tire,15,Frank,Lee
7,8,90,Mark,Schwarz,Bottle,10,Mary,NaN
8,9,20,Kevin,Brown,Bottle,10,Mary,NaN
9,10,60,Mary,NaN,Tire,15,Carol,Baker