# SQL FUNCTIONS

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_customers = pd.read_csv('data/sales_customers.csv')
df_employees = pd.read_csv('data/sales_employees.csv')
df_orders = pd.read_csv('data/sales_orders.csv')
df_orderarchive = pd.read_csv('data/sales_ordersarchive.csv')
df_products = pd.read_csv('data/sales_products.csv')

### String Functions

*Manipulation*
1. CONCAT
2. UPPER
3. LOWER
4. TRIM
5. REPLACE

*Calculation*
1. LEN

*String Extraction*
1. LEFT
2. RIGHT
3. SUBSTRING

### CONCAT

```SQL
SELECT
    firstname,
    country,
    CONCAT (firstname,' ',country) AS name_country
FROM sales.customers;
```

In [6]:
df_resultado = df_customers[['firstname','country']].copy()

df_resultado['name_country'] = df_resultado['firstname']+' '+df_resultado['country']

df_resultado

  firstname  country    name_country
0    Jossef  Germany  Jossef Germany
1     Kevin      USA       Kevin USA
2      Mary      USA        Mary USA
3      Mark  Germany    Mark Germany
4      Anna      USA        Anna USA

### UPPER and LOWER

```SQL
SELECT
    UPPER(firstname)
FROM sales.customers;

SELECT
    LOWER(firstname)
FROM sales.customers;
```

In [8]:
df_customers['firstname_upper'] = df_customers['firstname'].str.upper()

df_customers['firstname_lower'] = df_customers['firstname'].str.lower()

df_customers

,customerid,firstname,lastname,country,score,firstname_upper,firstname_lower
0,1,Jossef,Goldberg,Germany,350.0,JOSSEF,jossef
1,2,Kevin,Brown,USA,900.0,KEVIN,kevin
2,3,Mary,NaN,USA,750.0,MARY,mary
3,4,Mark,Schwarz,Germany,500.0,MARK,mark
4,5,Anna,Adams,USA,NaN,ANNA,anna

### TRIM

```SQL
SELECT
    TRIM(firstname)
FROM sales.customers;
```

In [9]:
df_customers['firstname_trim'] = df_customers['firstname'].str.strip()

df_customers

,customerid,firstname,lastname,country,score,firstname_upper,firstname_lower,firstname_trim
0,1,Jossef,Goldberg,Germany,350.0,JOSSEF,jossef,Jossef
1,2,Kevin,Brown,USA,900.0,KEVIN,kevin,Kevin
2,3,Mary,NaN,USA,750.0,MARY,mary,Mary
3,4,Mark,Schwarz,Germany,500.0,MARK,mark,Mark
4,5,Anna,Adams,USA,NaN,ANNA,anna,Anna

### REPLACE 

```SQL
SELECT
    '123-456-7890' AS phone,
    REPLACE('123-456-7890','-','') AS clean_phone
```

In [10]:
df = pd.DataFrame({'phone': ['123-456-7890','987-654-3210']})

df['clean_phone'] = df['phone'].str.replace( '-', '', regex=False)

df

          phone clean_phone
0  123-456-7890  1234567890
1  987-654-3210  9876543210

### CALCULATION

### LEN

```SQL
SELECT
    length(firstname)
FROM sales.customers;
```

In [12]:
df_customers['firstname_len'] = df_customers['firstname'].str.len()

df_customers

,customerid,firstname,lastname,country,score,firstname_upper,firstname_lower,firstname_trim,firstname_len
0,1,Jossef,Goldberg,Germany,350.0,JOSSEF,jossef,Jossef,6
1,2,Kevin,Brown,USA,900.0,KEVIN,kevin,Kevin,5
2,3,Mary,NaN,USA,750.0,MARY,mary,Mary,4
3,4,Mark,Schwarz,Germany,500.0,MARK,mark,Mark,4
4,5,Anna,Adams,USA,NaN,ANNA,anna,Anna,4

### LEFT and RIGHT

```SQL
SELECT
    LEFT(firstname,2),
    RIGHT(firstname, 2)
FROM sales.customers;
```

In [13]:
df_customers['first_2'] = df_customers['firstname'].str[:2]
df_customers['last_2'] = df_customers['firstname'].str[-2:]

df_customers

,customerid,firstname,lastname,country,score,firstname_upper,firstname_lower,firstname_trim,firstname_len,first_2,last_2
0,1,Jossef,Goldberg,Germany,350.0,JOSSEF,jossef,Jossef,6,Jo,ef
1,2,Kevin,Brown,USA,900.0,KEVIN,kevin,Kevin,5,Ke,in
2,3,Mary,NaN,USA,750.0,MARY,mary,Mary,4,Ma,ry
3,4,Mark,Schwarz,Germany,500.0,MARK,mark,Mark,4,Ma,rk
4,5,Anna,Adams,USA,NaN,ANNA,anna,Anna,4,An,na

### SUBSTRING (VAlUE, START, LENGTH)

```SQL
SELECT
    SUBSTRING(firstname, 2, LENGTH(firstname)) AS Sub_name
FROM sales.customers;
```

In [ ]:
df_customers['Sub_Name'] = df_customers['firstname'].str[1:]

df_customers

,customerid,firstname,lastname,country,score,firstname_upper,firstname_lower,firstname_trim,firstname_len,first_2,last_2,Sub_Name
0,1,Jossef,Goldberg,Germany,350.0,JOSSEF,jossef,Jossef,6,Jo,ef,ossef
1,2,Kevin,Brown,USA,900.0,KEVIN,kevin,Kevin,5,Ke,in,evin
2,3,Mary,NaN,USA,750.0,MARY,mary,Mary,4,Ma,ry,ary
3,4,Mark,Schwarz,Germany,500.0,MARK,mark,Mark,4,Ma,rk,ark
4,5,Anna,Adams,USA,NaN,ANNA,anna,Anna,4,An,na,nna

## FUNCTION NUMBER

- ROUND
- ABS

## DATE & TIME FUNCTIONS

- DATEPART
- DATENAME
- DATETRUNC
- EOMONTH

### GETDATE() | CURRENT_TIMESTAMP

#### Returns the current date and time at the moment when the query is executed

```SQL
SELECT
    orderid,
    creationtime,
    '2024-08-20'::DATE AS HardCoded,
    CURRENT_TIMESTAMP AS TODAY
FROM sales.orders;
```

### EXTRACT (YEAR FROM ...)

```SQL
SELECT
    orderid,
    creationtime,
    EXTRACT (YEAR FROM creationtime) AS order_year,
    EXTRACT (MONTH FROM creationtime) AS order_month,
    EXTRACT (DAY FROM creationtime) AS order_day,
    EXTRACT (HOUR FROM creationtime) AS order_hour,
    EXTRACT (MINUTE FROM creationtime) AS order_minute,
    EXTRACT (SECOND FROM creationtime) AS order_seconds
FROM sales.orders;
```

In [16]:
# Aseguramos que sea formato fecha
df_orders['creationtime'] = pd.to_datetime(df_orders['creationtime'])

# Extraemos cada componente
df_orders['order_year'] = df_orders['creationtime'].dt.year
df_orders['order_month'] = df_orders['creationtime'].dt.month
df_orders['order_day'] = df_orders['creationtime'].dt.day
df_orders['order_hour'] = df_orders['creationtime'].dt.hour
df_orders['order_minute'] = df_orders['creationtime'].dt.minute
df_orders['order_seconds'] = df_orders['creationtime'].dt.second

df_orders

,orderid,productid,customerid,salespersonid,orderdate,shipdate,orderstatus,shipaddress,billaddress,quantity,sales,creationtime,order_year,order_month,order_day,order_hour,order_minute,order_seconds
0,1,101,2,3,2025-01-01,2025-01-05,Delivered,9833 Mt. Dias Blv.,1226 Shoe St.,1,10,2025-01-01 12:34:56,2025,1,1,12,34,56
1,2,102,3,3,2025-01-05,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04,2025,1,5,23,22,4
2,3,101,1,5,2025-01-10,2025-01-25,Delivered,8157 W. Book,8157 W. Book,2,20,2025-01-10 18:24:08,2025,1,10,18,24,8
3,4,105,1,3,2025-01-20,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33,2025,1,20,5,50,33
4,5,104,2,5,2025-02-01,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41,2025,2,1,14,2,41
5,6,104,3,5,2025-02-05,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57,2025,2,6,15,34,57
6,7,102,1,1,2025-02-15,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01,2025,2,16,6,22,1
7,8,101,4,3,2025-02-18,2025-02-27,Shipped,2947 Vine Lane,4311 Clay Rd,3,90,2025-02-18 10:45:22,2025,2,18,10,45,22
8,9,101,2,3,2025-03-10,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04,2025,3,10,12,59,4
9,10,102,3,5,2025-03-15,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15,2025,3,16,23,25,15

### date_part

```SQL
SELECT
    orderid,
    creationtime,
    date_part('quarter', creationtime) as quarter_dp,
    date_part('week', creationtime) as week_dp
FROM sales.orders;
```

In [18]:
# Trimestre
df_orders['quarter_dp'] = df_orders['creationtime'].dt.quarter

# Semana (ISO)
df_orders['week_dp'] = df_orders['creationtime'].dt.isocalendar().week

df_orders

,orderid,productid,customerid,salespersonid,orderdate,shipdate,orderstatus,shipaddress,billaddress,quantity,sales,creationtime,order_year,order_month,order_day,order_hour,order_minute,order_seconds,quarter_dp,week_dp
0,1,101,2,3,2025-01-01,2025-01-05,Delivered,9833 Mt. Dias Blv.,1226 Shoe St.,1,10,2025-01-01 12:34:56,2025,1,1,12,34,56,1,1
1,2,102,3,3,2025-01-05,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04,2025,1,5,23,22,4,1,1
2,3,101,1,5,2025-01-10,2025-01-25,Delivered,8157 W. Book,8157 W. Book,2,20,2025-01-10 18:24:08,2025,1,10,18,24,8,1,2
3,4,105,1,3,2025-01-20,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33,2025,1,20,5,50,33,1,4
4,5,104,2,5,2025-02-01,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41,2025,2,1,14,2,41,1,5
5,6,104,3,5,2025-02-05,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57,2025,2,6,15,34,57,1,6
6,7,102,1,1,2025-02-15,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01,2025,2,16,6,22,1,1,7
7,8,101,4,3,2025-02-18,2025-02-27,Shipped,2947 Vine Lane,4311 Clay Rd,3,90,2025-02-18 10:45:22,2025,2,18,10,45,22,1,8
8,9,101,2,3,2025-03-10,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04,2025,3,10,12,59,4,1,11
9,10,102,3,5,2025-03-15,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15,2025,3,16,23,25,15,1,11

### DATENAME