# SQL NULL vs Empty String vs Blank Space

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_customers = pd.read_csv('data/sales_customers.csv')
df_employees = pd.read_csv('data/sales_employees.csv')
df_orders = pd.read_csv('data/sales_orders.csv')
df_orderarchive = pd.read_csv('data/sales_ordersarchive.csv')
df_products = pd.read_csv('data/sales_products.csv')

```SQL
WITH Orders AS (
    SELECT 1 Id, 'A' Category UNION
    SELECT 2, NULL UNION -- NULL
    SELECT 3, '' UNION -- Empy String
    SELECT 4, ' ' -- Blank Space
)
SELECT
    *,
    LENGTH(Category) AS CategoryLen
FROM Orders;
```

In [4]:
data = {
    'Id' : [1,2,3,4],
    'Category': ['A',None,'',' ']
}
df = pd.DataFrame(data)

df['CategoryLen'] = df['Category'].str.len()

df

   Id Category  CategoryLen
0   1        A          1.0
1   2     None          NaN
2   3                   0.0
3   4                   1.0

### DATA POLICIES

#### Set of rules that defines how data should be handled

1. Only use NULLs and empty strings, but avoid blank spaces (USE TRIM)

```SQL
WITH Orders AS (
    SELECT 1 Id, 'A' Category UNION
    SELECT 2, NULL UNION
    SELECT 3, '' UNION
    SELECT 4, ' '
)
SELECT
    *,
    LENGTH(TRIM(Category)) AS CategoryLen
FROM Orders;
```

In [7]:
df2 = pd.DataFrame(data)

df2['categorylen'] = df2['Category'].str.strip().str.len()

df2

   Id Category  categorylen
0   1        A          1.0
1   2     None          NaN
2   3                   0.0
3   4                   0.0

### 2 DATA POLICY

2. Only use NULLS and avoid using empty strings and blanck spaces

```SQL
WITH Orders AS (
    SELECT 1 Id, 'A' Category UNION
    SELECT 2, NULL UNION
    SELECT 3, '' UNION
    SELECT 4, ' '
)
SELECT
    *,
    NULLIF(TRIM(Category),'') AS null_empty
FROM Orders;
```

In [15]:
df3 = pd.DataFrame(data)

df3['Category'] = df3['Category'].str.strip()

df3['Category'] = df3['Category'].replace('', np.nan)

df3['Category'] = df3['Category'].fillna(value=np.nan)

df3

   Id Category
0   1        A
1   2      NaN
2   3      NaN
3   4      NaN

### 3 DATA POLICY

3. Use the default value 'unknown' and avoid using nulls, empty strings, and blanck spaces

```SQL
WITH Orders AS (
    SELECT 1 Id, 'A' Category UNION
    SELECT 2, NULL UNION
    SELECT 3, '' UNION
    SELECT 4, ' '
)
SELECT
    COALESCE(NULLIF(TRIM(Category),''), 'unknown') AS Policy3
FROM Orders;
```

In [16]:
df4 = pd.DataFrame(data)

df4['Policy3'] = (
    df['Category'].str.strip().replace('', np.nan).fillna('unknown')
)

df4

   Id Category  Policy3
0   1        A        A
1   2     None  unknown
2   3           unknown
3   4           unknown