# Amazon - Marketing Segment Strategy Cross-Brand Alignment

In [2]:
import pandas as pd    
import numpy as np
import polars as pl
from datetime import date

In [3]:
df_segment = pd.read_csv('../Data/005/dim_segment.csv')
df_brand = pd.read_csv('../Data/005/brand_score_metrics.csv', parse_dates=['metric_date'])

pl_segment = pl.read_csv('../Data/005/dim_segment.csv')
pl_brand = pl.read_csv('../Data/005/brand_score_metrics.csv', try_parse_dates=True)

# Pregunta 1

### El equipo de Marketing quiere comenzar su evaluación de los mensajes de marca para el cuarto trimestre (Q4) de 2024. ¿Podrías proporcionar una lista de los mensajes clave (key_message) y los detalles del puntaje de marca (brand_score) registrados entre el 1 de octubre de 2024 y el 31 de diciembre de 2024?

```SQL
SELECT
    key_message,
    brand_score
FROM brand_score_metrics
WHERE metric_date BETWEEN '2024-10-01' AND '2024-12-31';
```

In [5]:
res = df_brand[
    df_brand['metric_date'].between('2024-10-01','2024-12-31')
]

res = res[['key_message', 'brand_score']]

In [7]:
res = pl_brand.filter(
    pl.col('metric_date').is_between(date(2024,10,1),date(2024,12,31))
).select([
    'key_message', 'brand_score'
])

# Pregunta 2

### Para un análisis más enfocado, el equipo de Marketing necesita los mensajes clave (key_message) y los detalles del puntaje de marca (brand_score) para el segmento AWS (representado por segment_id = 2) en el cuarto trimestre (Q4) de 2024, pero solo para los registros donde el puntaje de marca sea igual o superior a 90. ¿Podrías recuperar estos detalles?

```SQL
SELECT
    key_message,
    brand_score
FROM brand_score_metrics
WHERE (metric_date BETWEEN '2024-10-01' AND '2024-12-31') AND
      (segment_id = 2) AND (brand_score >= 90);
```

In [9]:
res = df_brand[
    (df_brand['metric_date'].between('2024-10-01','2024-12-31')) &
    (df_brand['segment_id'] == 2) & (df_brand['brand_score'] >= 90)
]

res = res[['key_message','brand_score']]

In [11]:
res = pl_brand.filter(
    (pl.col('metric_date').is_between(date(2024,10,1),date(2024,12,31))) &
    (pl.col('segment_id') == 2) & (pl.col('brand_score') >= 90)
).select([
    'key_message', 'brand_score'
])

# Pregunta 3

### Para revisar rápidamente un resumen de los hallazgos, al equipo de Marketing le gustaría ver una muestra de los mensajes clave (key_message) y los detalles del puntaje de marca (brand_score) para el segmento de Entretenimiento (representado por segment_id = 3) con un puntaje de marca superior a 80. ¿Podrías proporcionar los 5 registros más recientes que cumplan con estos criterios?

```SQL
SELECT
    key_message,
    brand_score
FROM brand_score_metrics
WHERE (segment_id = 3) AND (brand_score > 80)
ORDER BY metric_date DESC
LIMIT 5;
```

In [20]:
res = df_brand[
    (df_brand['segment_id'] == 3) &
    (df_brand['brand_score'] > 80)
]

res = res.sort_values('metric_date', ascending=False).head(5).reset_index(drop=True)

res = res[['key_message', 'brand_score']]

res

                                         key_message  brand_score
0  Entertaining audiences with groundbreaking series         83.0
1           Festive specials capture family memories         92.0
2           Delivering immersive viewing experiences         82.0
3             Engaging digital narratives win hearts         81.5
4              Quality content with a personal touch         88.0

In [23]:
res = pl_brand.filter(
    (pl.col('segment_id') == 3) &
    (pl.col('brand_score') > 80)
).sort('metric_date', descending=True).head(5).select([
    'key_message', 'brand_score'
])

res

shape: (5, 2)
┌─────────────────────────────────┬─────────────┐
│ key_message                     ┆ brand_score │
│ ---                             ┆ ---         │
│ str                             ┆ f64         │
╞═════════════════════════════════╪═════════════╡
│ Entertaining audiences with gr… ┆ 83.0        │
│ Festive specials capture famil… ┆ 92.0        │
│ Delivering immersive viewing e… ┆ 82.0        │
│ Engaging digital narratives wi… ┆ 81.5        │
│ Quality content with a persona… ┆ 88.0        │
└─────────────────────────────────┴─────────────┘