# Netflix - User Engagement in Interactive Content

In [1]:
import pandas as pd
import numpy as np
import polars as pl
from datetime import date

In [13]:
df_choices = pd.read_csv('../Data/020/choices_made.csv', parse_dates=['choice_date'])
df_viewer = pd.read_csv('../Data/020/viewer_interactions.csv', parse_dates=['interaction_date'])

pl_choices = pl.read_csv('../Data/020/choices_made.csv', try_parse_dates=True)
pl_viewer = pl.read_csv('../Data/020/viewer_interactions.csv', try_parse_dates=True)

# Pregunta 1

### Utilizando la tabla viewer_interactions, ¿cuántos espectadores únicos han interactuado con cualquier contenido interactivo en octubre de 2024? ¿Puedes encontrar el número de espectadores distintos?

```SQL
SELECT
    COUNT(DISTINCT viewer_id) AS cantidad_espectadores_unicos
FROM viewer_interactions
WHERE ((EXTRACT(MONTH FROM interaction_date) = 10) AND
       (EXTRACT(YEAR FROM interaction_date) = 2024))
```

In [5]:
oct = df_viewer[
    (df_viewer['interaction_date'].dt.month == 10) &
    (df_viewer['interaction_date'].dt.year == 2024)
].reset_index()

res = oct['viewer_id'].nunique()

In [7]:
res = pl_viewer.filter(
    (pl.col('interaction_date').dt.month() == 10) &
    (pl.col('interaction_date').dt.year() == 2024)
).select(
    pl.col('viewer_id').n_unique()
).item()

res

5

# Pregunta 2

### Para entender las preferencias de los espectadores, el equipo desea una lista de todas las elecciones únicas realizadas por los espectadores en noviembre de 2024. ¿Puedes proporcionar esta lista ordenada alfabéticamente por la descripción de la elección?

```SQL
SELECT
    DISTINCT choice_description AS choice_description_unique
FROM choices_made
WHERE ((EXTRACT(MONTH FROM choices_made.choice_date) = 11) AND
       (EXTRACT(YEAR FROM choices_made.choice_date) = 2024))
ORDER BY choice_description ASC
```

In [ ]:
nov = df_choices[
    (df_choices['choice_date'].dt.month == 11) &
    (df_choices['choice_date'].dt.year == 2024)
].reset_index()

res = nov['choice_description'].drop_duplicates().sort_values()

AttributeError: 'Series' object has no attribute 'sort'

In [19]:
res = pl_choices.filter(
    (pl.col('choice_date').dt.month() == 11) &
    (pl.col('choice_date').dt.year() == 2024)
).select(
    pl.col('choice_description').unique().sort(descending=False)
)

# Pregunta 3

### El equipo está interesado en entender qué espectadores interactuaron con el contenido pausando el video en diciembre de 2024. ¿Puedes proporcionar una lista de los IDs de los espectadores que realizaron esta acción?

```SQL
SELECT
    DISTINCT viewer_id
FROM viewer_interactions
WHERE ((EXTRACT(MONTH FROM interaction_date) = 12) AND
       (EXTRACT(YEAR FROM interaction_date) = 2024)) AND
    interaction_type = 'pause';
```

In [27]:
dic = df_viewer[
    (df_viewer['interaction_date'].dt.month == 12) &
    (df_viewer['interaction_date'].dt.year == 2024) &
    (df_viewer['interaction_type'] == 'pause')
].reset_index()

res = dic[['viewer_id']].drop_duplicates()

res

   viewer_id
0        105
1        108

In [29]:
res = pl_viewer.filter(
    (pl.col('interaction_date').dt.month() == 12) &
    (pl.col('interaction_date').dt.year() == 2024) &
    (pl.col('interaction_type') == 'pause')
).select(
    pl.col('viewer_id').unique()
)

res

shape: (2, 1)
┌───────────┐
│ viewer_id │
│ ---       │
│ i64       │
╞═══════════╡
│ 105       │
│ 108       │
└───────────┘