# 001 - Estructura y Selección

In [1]:
import pandas as pd
import numpy as np
import polars as pl

In [6]:
df_customers = pd.read_csv('../data/sales_customers.csv')
df_employees = pd.read_csv('../data/sales_employees.csv')
df_orders = pd.read_csv('../data/sales_orders.csv')
df_orderarchive = pd.read_csv('../data/sales_ordersarchive.csv')
df_products = pd.read_csv('../data/sales_products.csv')

pl_customers = pl.read_csv('../data/sales_customers.csv')
pl_employees = pl.read_csv('../data/sales_employees.csv')
pl_orders = pl.read_csv('../data/sales_orders.csv')
pl_orderarchive = pl.read_csv('../data/sales_ordersarchive.csv')
pl_products = pl.read_csv('../data/sales_products.csv')

# 📝 Reto Fase 1: Selección y Alias
Imagina que el Gerente de Ventas te pide un reporte rápido de los productos disponibles, pero lo quiere con nombres específicos para que sea más fácil de leer en una presentación.

La pregunta: Extrae de la tabla sales_products.csv las columnas product y price, pero cámbiales el nombre para que se vean como Nombre_Producto y Precio_Unitario respectivamente.

```SQL
SELECT
    product AS Nombre_Producto,
    price AS Precio_Unitario
FROM sales.products;
```

In [16]:
# PANDAS
df_p = df_products.copy()

resultado = df_products[['product','price']].rename(
    columns={'product': 'Nombre_Producto', 'price':'Precio_Unitario'}
)

resultado

  Nombre_Producto  Precio_Unitario
0          Bottle               10
1            Tire               15
2           Socks               20
3            Caps               25
4          Gloves               30

In [19]:
pl_p = pl_products

resultado_pl = pl_p.select([
    pl.col('product').alias('Nombre_Producto'),
    pl.col('price').alias('Precio_Unitario')
])

resultado_pl

shape: (5, 2)
┌─────────────────┬─────────────────┐
│ Nombre_Producto ┆ Precio_Unitario │
│ ---             ┆ ---             │
│ str             ┆ i64             │
╞═════════════════╪═════════════════╡
│ Bottle          ┆ 10              │
│ Tire            ┆ 15              │
│ Socks           ┆ 20              │
│ Caps            ┆ 25              │
│ Gloves          ┆ 30              │
└─────────────────┴─────────────────┘

# 📝 Mini-Reto Final Fase 1 (Para cerrar con broche de oro)

De la tabla sales_customers.csv, selecciona firstname, lastname y score. Pero llámalos: Nombre, Apellido y Puntaje. 

```SQL
SELECT
    firstname AS Nombre,
    lastname AS Apellido,
    score AS Puntaje
FROM sales.customers;
```

In [24]:
#Pandas

df_c = df_customers.copy()

respuesta = df_c[['firstname','lastname','score']].rename(
    columns={'firstname':'Nombre','lastname':'Apellido', 'score':'Puntaje'}
)

respuesta

   Nombre  Apellido  Puntaje
0  Jossef  Goldberg    350.0
1   Kevin     Brown    900.0
2    Mary       NaN    750.0
3    Mark   Schwarz    500.0
4    Anna     Adams      NaN

In [ ]:
# Polars
pl_c = pl_customers

respuesta = pl_c.select([
    pl.col('firstname').alias('Nombre'),
    pl.col('lastname').alias('Apellido'),
    pl.col('score').alias('Puntaje')
])

respuesta

shape: (5, 3)
┌────────┬──────────┬─────────┐
│ Nombre ┆ Apellido ┆ Puntaje │
│ ---    ┆ ---      ┆ ---     │
│ str    ┆ str      ┆ i64     │
╞════════╪══════════╪═════════╡
│ Jossef ┆ Goldberg ┆ 350     │
│ Kevin  ┆ Brown    ┆ 900     │
│ Mary   ┆ null     ┆ 750     │
│ Mark   ┆ Schwarz  ┆ 500     │
│ Anna   ┆ Adams    ┆ null    │
└────────┴──────────┴─────────┘

# 📝 El Reto Final de la Fase 1 (Combinado)
Vamos a juntar todo lo aprendido en la Fase 1. Usando la tabla sales_orders.csv, necesito que hagas lo siguiente:

Selecciona la columna orderstatus.

Asegúrate de que los valores no se repitan (queremos ver los estados únicos de las órdenes).

Cambia el nombre de la columna a Estado_Unico.

Muestra solo los primeros 2 resultados.

```SQL
SELECT
    DISTINCT orderstatus AS Estado_Unico
FROM sales.orders
LIMIT 2;
```

In [30]:
# Pandas
df_o = df_orders.copy()

respuesta = df_o[['orderstatus']].drop_duplicates().rename(columns={'orderstatus':'EStadoUnico'}).head(2)

respuesta

  EStadoUnico
0   Delivered
1     Shipped

In [32]:
# Polars
pl_o = pl_orders

respuesta = pl_o.select(pl.col('orderstatus').alias('Estado_Unico')).unique().head(2)

respuesta

shape: (2, 1)
┌──────────────┐
│ Estado_Unico │
│ ---          │
│ str          │
╞══════════════╡
│ Delivered    │
│ Shipped      │
└──────────────┘